runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
- url: /static
  static_dir: static
- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
# [END handlers]
